# -*- coding: utf-8 -*-
"""object detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YpLEEf4JK3tU_vUgxR7QpZPqjvrKoa8S
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/grive')

# Commented out IPython magic to ensure Python compatibility.
# %cd grive/MyDrive/yolo

!pip install ultralytics -q

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo  checks

"""fine_tune a pre-train model on my data set"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile yolo.yaml
# 
# train: /content/grive/MyDrive/yolo/images
# val:  /content/grive/MyDrive/yolo/images
# 
# #class name
# nc: 28 # number of classes
# names: [ 'dog',
# 'person',
# 'cat',
# 'tv',
# 'car',
# 'meatballs',
# 'marinara sauce',
# 'tomato soup',
# 'chicken noodle soup',
# 'french onion soup',
# 'chicken breast',
# 'ribs','pulled pork',
# 'hamburger',
# 'cavity',
# 'no parking',
# 'stop sign',
# 'double curve',
# 'curve sign',
# 'priority road',
# 'no stopping by',
# 'traffic light',
# 'speed sign ',
# 'no entry ',
# 'road narrow' ,
# 'give away',
# 'loose chippings',
# 'traffic lightt']
#

!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source=/content/grive/MyDrive/yolo/images save=True data='/content/grive/MyDrive/yolo/yolo.yaml'

"""model from scrach with random weight on my dataset

"""

!yolo task=detect mode=train model=yolov8m.pt data ='/content/grive/MyDrive/yolo/yolo.yaml' epochs = 20 patience=0 weight_decay = 0.0003 lr0 = 0.2

Image(filename='/content/grive/MyDrive/yolo/runs/detect/train43/results.png',height=500)

!yolo task=detect mode=predict model=/content/grive/MyDrive/yolo/runs/detect/train43/weights/best.pt conf=0.25 source=/content/grive/MyDrive/yolo/images

!yolo task=detect mode=predict model=/content/grive/MyDrive/yolo/runs/detect/train43/weights/best.pt conf=0.25 source=/content/grive/MyDrive/yolo/test.mp4 save=True

